### ISSUE TITLE
Cloud Expert Services should not appear in the list of Compute Services

### ISSUE THREAD

**Issue by lionelmace** [l2fprod/mycatalog#23]
@l2fprod 

![image](https://user-images.githubusercontent.com/12241613/121935028-45f5ad00-cd48-11eb-882a-4da56aa02b73.png)

**Comment by l2fprod** [comment]
it's the vmware tag

![image](https://user-images.githubusercontent.com/12746550/121936565-62292800-cd0f-11eb-970d-3c66b072e9ce.png)

but this service is also metadata.ui.hidden = true -- I guess we can just remove all these services from mycatalog

**Comment by l2fprod** [comment]
removed all services with `metadata.ui.hidden == true`
