### ISSUE TITLE
Classic Infrastructure is available in Chennai 

### ISSUE THREAD

**Issue by itsdeepakrai** [l2fprod/mycatalog#26]
Hi team, 
Just adding this issue where, VSI, BareMetal on Classic, IKS n ROKS classic is available in Chennai DC. But its not reflecting in the mycatalog .

**Comment by l2fprod** [comment]
now showing when you select Data Centers (vs Region)

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/12746550/213523285-1f8bbee8-1d2f-4c3c-a519-526e656dd209.png">
