### ISSUE TITLE
FR - Include "Type" to filter on services, software, deployable architectures

### ISSUE THREAD

**Issue by sethjano** [l2fprod/mycatalog#29]
Great work guys.  Would it possible to include "Type" in the catalog tool?  

![Screenshot 2023-10-02 at 12 37 23 PM](https://github.com/l2fprod/mycatalog/assets/43014103/60ea4def-9ec6-4ee6-9469-129758aad4ca)

**Comment by l2fprod** [comment]
mycatalog does not list software or deployable architectures, only services
